apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2026-09-23T18:53:08Z"
    labels:
      app: mealie
    name: mealie
    namespace: mealie-ns
    resourceVersion: "65478"
    uid: ce2dde7d-db0d-4020-8e44-5bfc41e4d436
  spec:
    clusterIP: 10.43.53.111
    clusterIPs:
    - 10.43.53.111
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 9000
    selector:
      app: mealie
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
